### ISSUE TITLE
Issue when attempting to use add-on

### ISSUE THREAD

**Issue by newman1080** [johnpincock/SpecialFields#1]
When attempting to import with the add-on enabled and all of my special fields "protected", I am getting the following notification upon import:

Import failed.
Traceback (most recent call last):
  File "aqt\importing.py", line 334, in importFile
  File "anki\importing\apkg.py", line 38, in run
  File "anki\importing\anki2.py", line 29, in run
  File "anki\importing\anki2.py", line 54, in _import
  File "C:\Users\justi\AppData\Roaming\Anki2\addons21\1102281552\__init__.py", line 364, in newImportNotes
    self._logNoteRow(_("Added"), row)
AttributeError: 'AnkiPackageImporter' object has no attribute '_logNoteRow'

**Comment by newman1080** [comment]
Updated to the newest version of anki and everything worked flawlessly.
