### ISSUE TITLE
Import of AnKing Overhaul not working during Upgrade

### ISSUE THREAD

**Issue by KellerChad** [johnpincock/SpecialFields#20]
When I try to import the AnKing Step 1 V7 deck I get the following error on Anki 2.1.29:

Import failed. Debugging info:
Traceback (most recent call last):
  File "aqt/importing.py", line 404, in on_done
  File "concurrent/futures/_base.py", line 432, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "anki/importing/apkg.py", line 44, in run
  File "anki/importing/anki2.py", line 41, in run
  File "anki/importing/anki2.py", line 64, in _import
  File "/Users/chadkeller/Library/Application Support/Anki2/addons21/1102281552/__init__.py", line 72, in newImportNotes
    shouldAdd = self._uniquifyNote(note)
  File "anki/importing/anki2.py", line 189, in _uniquifyNote
  File "/Users/chadkeller/Library/Application Support/Anki2/addons21/1102281552/__init__.py", line 255, in _mid
    self.dst.models.update(model)
  File "anki/models.py", line 231, in update
  File "anki/rsbackend_gen.py", line 414, in add_or_update_notetype
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.InvalidInput: InvalidInput { info: "attempt to save stale notetype" }

I have watched the video and selected the update settings in the add-on, but I have not been able to import the deck. Thank you for your time and I hope you are able to help!

**Comment by dae** [comment]
Seems to be affecting a number of users:

https://forums.ankiweb.net/t/special-fields-error-on-2-1-30/2203
